templates/base.html
templates/publicdashboards.html
templates/report_base.html

Tola's brand font, Scandia, is now added to the bottom of layouts' `body` element.
This PR also includes a minor HTML syntax fix across all layouts.

Add Web Fonts

---

templates/customdashboard/notebook.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toladata/tolaactivity/283)

replace text code with dynamic reference needed

---

templates/workflow/programdashboard_list.html
workflow/forms.py
workflow/models.py
workflow/views.py

#639: Display correct corresponding agreemnets  on the project dashboard

---

templates/workflow/projectcomplete_form.html
workflow/forms.py
workflow/views.py

Prevent updating PI form components when PT components are added

Fixes on issue #619: 

---

Dockerfile.dev
README.md
docker-compose-dev.yml
docker-entrypoint-dev.sh
requirements-dev.txt
tola/settings/local.py

Refactor the instructions and prepare the environment to develop in local.

Docker local deployment

---

README.md
feed/views.py
tola/urls.py

https://github.com/toladata/TolaDataV2/issues/233

#233 Indicator Reporting Frequency filtered by Org

---

requirements.txt

Just some random improvements I did.

Clean up requirements

---

.drone.yml

In a pull request we don't need to build the container, but just running tests.

Disable drone building for PR

---

.travis.yml
feed/test.py
feed/test_views.py
feed/views.py
manage.py
tola/middleware.py
tola/settings/test.py

https://github.com/toladata/TolaDataV2/issues/328

Fix CheckList DB error #328

---

feed/admin.py
feed/permissions.py
feed/serializers.py
feed/tests/test_checklistview.py
feed/tests/test_workflowlevel1view.py
feed/views.py
tola/views.py
workflow/models.py

https://github.com/toladata/TolaDataV2/issues/338
Any user that creates a new Program is not the admin of it, unless they make an extra API call in the frontend to add it. This PR solves this problem.

Add user as ProgramAdmin to WorkflowLevel1 (Program) #338

---

feed/tests/test_contactview.py
feed/views.py
tola/util.py

Fix API errors and create unit tests for them.
Related issues: #747

Fix Contact API Error

---

formlibrary/models.py
indicators/models.py
search/models.py
workflow/models.py

In our code we have timezone activated. Somehow, when we are setting up the dates in database, we are not including such information. This fixes that wrong behaviour.

Fix runtime error datetime

---

feed/serializers.py
feed/views.py

Change perform_create of view to add org instead of the serializer create method.
Related issue: TolaDataV2/[#414](https://github.com/toladata/TolaDataV2/issues/414)

Change perform_create of view to add org instead

---

factories/user_models.py
feed/permissions.py
feed/tests/test_workflowlevel1view.py
feed/views.py
workflow/models.py

Purpose
======
Fixes any kind of edition for Program.
https://github.com/toladata/TolaDataV2/issues/400

Program (Workflowlevel1) edition errors fix #400

---

.gitignore
.travis.yml
README.md
feed/tests/test_approvalworkflowview.py
indicators/models.py
requirements-ci.txt

Purpose
=====
Creates metrics for code coverage.

Add code coverage and do fixes

---

.coveragerc

Purpose
=====
Exclude certain directories from the reports.

Adjust coverage reports

---

feed/permissions.py
feed/tests/test_workflowlevel1view.py
feed/views.py
workflow/models.py

Purpose
=====
Fixes permissions for program edition:
https://github.com/toladata/TolaDataV2/issues/400
Also fixes permissions for destroy method.

Workflowlevel1 edition permissions #400

---

feed/permissions.py
feed/tests/test_indicatorview.py
feed/views.py
indicators/models.py

Purpose
=====
Permissions: https://docs.google.com/spreadsheets/d/1mWGhO-Acin5SQnfOrHm58UCY3Y965x98fk9i6-ozpq0/edit#gid=0
Ticket: https://github.com/toladata/TolaDataV2/issues/360

Fix Indicator delete #360

---

factories/workflow_models.py
tola/management/commands/loaddemo.py

Purpose
======
We need a way to setup a default organization (TolaData) and set of Demo programs and related data that every new user is automatically added to.
Approach
=======
Created a custom django-admin command to create those data using the _factory boy_.
Related issue: #780

Default Org and Program

---

feed/tests/test_tolauserview.py
feed/views.py
indicators/forms.py
tola/util.py

Purpose
=====
List users only by org.
Ticket
====
https://github.com/toladata/TolaDataV2/issues/455

List users by organization #455

---

factories/indicators_models.py
feed/tests/test_frequencyview.py
feed/views.py

Purpose
======
Fix a non defined variable error recently introduced.

Fix frequency list view error

---

feed/permissions.py
feed/tests/test_collecteddataview.py
feed/tests/test_contactview.py
feed/tests/test_levelview.py
feed/tests/test_objectiveview.py

A user with the role OrgAdmin shouldn't be able to change things from another organization.
Related issue: #825

Fix OrgAdmin permission

---

feed/permissions.py
feed/tests/test_browseableapi.py
tola/settings/base.py

Restrict access to browse-able API with session to the super user only.
Related issue: #823

Add custom permission to browseable API

---

docker-compose-dev.yml
requirements-ci.txt
requirements-dev.txt
templates2/index.html
templates2/registration/privacy_policy.html
templates2/registration/register.html
tola/forms.py
tola/settings/dev.py
tola/settings/local.py
tola/tests/test_views.py
tola/urls.py
tola/views.py

Purpose
======
As soon as we split the Community Edition we won't need TolaSites anymore. I splitted as much as possible the code requiring TolaSites so we are prepared to do the fork faster.
Ticket
=====
https://github.com/toladata/TolaActivity/issues/820

TolaSite settings fallbacks #820

---

feed/tests/test_indicatorview.py
feed/tests/test_workflowlevel1view.py
feed/tests/test_workflowteamview.py
feed/views.py

OrgAdmin should be able to create an indicator for a program and see it afterward.
Related ticket: #845

Fix the filter of some list views

---

templates2/index.html
tola/tests/test_views.py
tola/views.py

Purpose
=======
Fixes a blocker.
Ticket
====
https://github.com/toladata/TolaActivity/issues/860

Build properly Track URL in frontpage

---

Dockerfile
docker-entrypoint.sh
docker/etc/nginx/nginx.conf

Add nginx as static file server layer and reverse proxy infront of the wsgi process

Serve static files

---

docker-entrypoint-dev.sh

Purpose
=====
Make Dev server startup faster and avoid unnecessary extra steps.

Do not generate migration files on Dev entrypoint

---

templates2/registration/login.html

Changed the Registration link text #638

---

requirements-ci.txt
requirements-dev.txt
requirements.txt

Purpose
======
We need the new factories in the Demo server, so it can't be an optional requirement anymore.

Make factory_boy as main requirement

---

feed/permissions.py
feed/tests/test_customformview.py
feed/views.py

Some permissions have changes and the behavior of the view set.
Related issue: #884

Update CustomForm viewset and permissions

---

tola/__init__.py
tola/forms.py
tola/management/commands/loadinitialdata.py
tola/management/commands/tests/test_loadinitialdata.py
tola/tests/test_views.py
workflow/__init__.py
workflow/apps.py
workflow/models.py
workflow/signals.py
workflow/tests/test_signals.py

Purpose
=======
All Demo Users should have Workflow Teams access to the default WFL1:
"Humanitarian Response to the Syrian Crisis".
Ticket
=====
https://github.com/toladata/TolaDataV2/issues/641

Assign demo users to default Program #641

---

templates2/index.html

Improved styling of the notification text on the index page #667

---

feed/tests/test_budgetview.py
workflow/models.py

When a budget is added to a program associated with a project budget module, the total summed up budget should be shown in the project dashboard.
Related ticket: TolaDataV2/[#677](https://github.com/toladata/TolaDataV2/issues/677)

Update Budget to compute actual and budget for wkfl2

---

tola/auth_pipeline.py
tola/tests/test_oauth.py

Related ticket: TolaDataV2?[#657](https://github.com/toladata/TolaDataV2/issues/657)

Update social auth pipeline to allow only the users in the whitelist

---

tola/management/commands/loadinitialdata.py
tola/management/commands/tests/test_loadinitialdata.py
workflow/signals.py
workflow/tests/test_signals.py

We need to have a new Project for German demo users, so they can test Activity.
https://github.com/toladata/TolaActivity/issues/901

Create factory default German Program #901

---

tola/auth_pipeline.py

Fix response of auth_allowed function

---

workflow/admin.py
workflow/models.py

Fix imports in workflow admin and models

---

factories/workflow_models.py
tola/management/commands/loadinitialdata.py
tola/management/commands/tests/test_loadinitialdata.py

Purpose
=====
Ability to run `loadinitialdata --restore` to get back again the demo data.
Ticket
====
https://github.com/toladata/TolaActivity/issues/905

Create a restore Demo data command option #905

---

search/test_utils.py
tola/management/commands/loadinitialdata.py
tola/management/commands/tests/test_loadinitialdata.py
tola/tests/test_views.py
workflow/tests/test_signals.py

Purpose
======
We don't really know when you are running the command what's doing inside. This improves that situation.

Add messages to loadinitialdata #905

---

search/utils.py

Purpose
======
Some small fix to make it more package-friendly in the near future.

Fix Elasticsearch logic

---

feed/serializers.py
feed/tests/test_disaggregationtypeview.py
feed/views.py

Purpose
=====
Fixes POST requests to /api/disaggregationtype/
Ticket
====
https://github.com/toladata/TolaActivity/issues/928

Fix POST DisaggregationType #928

---

templates2/registration/privacy_policy.html
tola/tests/test_views.py

Ticket
====
https://github.com/toladata/TolaDataV2/issues/683

Update privacy policy

---

Dockerfile
docker-entrypoint.sh
docker/etc/nginx/tola.conf
tola/settings/local.py

Purpose
======
I'm not sure it will work, but I tried something similar on local and works.

Use NGINX as a reverse proxy and static file server

---

setup.py
tola/management/commands/tests/test_loadinitialdata.py

Purpose
======
Needed for ActivityAPI manage.py migrate.

Add search app migrations to pkg

---

feed/tests/test_workflowlevel1view.py
feed/views.py
tola/auth_pipeline.py
tola/tests/test_oauth.py
tola/tests/test_track_sync.py
tola/tests/test_views.py
tola/track_sync.py
tola/util.py
tola/views.py

When a user creates a program on Activity it should be created on Track as well.
Related ticket: #940

Sync workflowlevel1 between Activity and Track

---

feed/views.py
search/views.py
tola/util.py

Purpose
======
Some clean up and logic changes.

Imports restructure

---

tola/tests/test_track_sync.py
tola/track_sync.py

Update track synchronization functions

---

feed/tests/test_workflowteamview.py
feed/views.py

We need to add this new filter in the workflowteam endpoint, so the Track can know which program a user is allowed to access.
Related ticket: TolaTables/[#394](https://github.com/toladata/TolaTables/issues/394)

Add a new filter in the workflowteam endpoint

---

search/Readme.md
setup.py

Modified setup.py to add search views and urls in external installations.
Also added search Readme documentation.

Added setup configuration for search views and urls

---

tola/management/commands/loadinitialdata.py

Documentation update for API
Used the help_text attribute to update docs and cleaned up unused field
Previous merge was overwritten by remote update

Workflow api docs

---

setup.py
tola/management/commands/tests/test_synctrack.py

We need to have the command to sync with Track in the package.
Related ticket: #1021

Add django-admin command synctrack to the package

---

.drone.yml

We don't need to trigger the deployment anymore. We only need the build and test.
Related ticket: No ticket

Remove the trigger-deployment from the drone file

---

tola/management/commands/synctrack.py

Filter the programs and projects correctly during the sync.
Updated the params of the filter.
Related ticket: #1026

Update methods in synctrack

---

tola/tests/test_track_sync.py
tola/track_sync.py

Fixes UTF-8 problems when logging.
_Related ticket: #1028_

Support Track sync with UTF-8 characters

---

ENVIRONMENT.md
README.md

Added a documentation for all environment variables that need to be set for the application to work correctly.
Listing all variables in a single file and explaining what they do
Always keep in mind to update this whenever we introduce new environment variables.

Added documentation for Environment variables

---

workflow/models.py

Adds new statuses to the project.
Related ticket: https://github.com/Humanitec/midgard/issues/87

Add new progress statuses to the Project

---

workflow/signals.py
workflow/tests/test_signals.py

Change the way that we validate the number of seats to notify the Org admins.
Instead of checking the add-ons, we're using the plan's quantity.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/177

Update the ChargeBee seats validation to use plan quantity

---

ENVIRONMENT.md
factories/workflow_models.py

To be able to make tests with ApprovalWorkflow, we need to add it to the factories.
@Menda I forgot to update the ChargeBee info in the **ENVIRONMENT** file, so I'm adding it to this simple PR.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/131

Add ApprovalWorkflow to factories

---

factories/workflow_models.py
workflow/admin.py
workflow/models.py
workflow/tests/test_models.py

Reverts toladata/TolaActivity#1084
There are migration files missing.

Revert " Remove Contact model from workflow module"

---

.travis.yml

Checks when building Travis if makemigrations was not executed.
Related ticket: None

Check missing migrations build

---

requirements/pkg.txt

I tried locally and looks alright. I need it for https://github.com/Humanitec/django-oauth-toolkit-jwt

Upgrade Django OAuth Toolkit

---

requirements/pkg.txt

Related ticket: https://github.com/Humanitec/ActivityAPI/issues/302

Upgrade django-oauth-toolkit-jwt to v0.2

---

requirements/base.txt
requirements/dev.txt
tola/settings/base.py

Delete unused requirements

---

workflow/migrations/0024_auto_20180620_0537.py

Fix the dashboard migration script number 24. I'm getting the following error when try to migrate.
```
Running migrations:
Applying workflow.0024_auto_20180620_0537...Traceback (most recent call last):
File "./manage.py", line 23, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line …
```

Fix the dashboard migration for UUID

---

factories/indicators_models.py

Add ReportingPeriod to the factories, so we can create demo data and test.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/379

Add a factory for ReportingPeriod

---

workflow/signals.py
workflow/tests/test_signals.py

Org admins get notification of exceeded seats when organization has more seats than available and if role one of users who has seat changed. But user still has same seat onlt its role changed. So, we need to remove this extra notification.
New flag added to check user has already seat and notification allowed to when user has no seat gains a seat.
_Related ticket: humanitec/ActivityAPI#284

fix #284 - remove extra notification of exceeded seats when updating wfl role

---

factories/workflow_models.py

We need to have in Internationalization in the factories for tests.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/428

Add the Internationalization model to factories

---

workflow/models.py
workflow/signals.py
workflow/tests/test_signals.py

Project's total_estimated_budget and actual_cost should be updated in the Budget model's signal.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/419

Create signal to calculate budgets

---

factories/indicators_models.py

We need to create a factory for TolaTable as well, so we can create tests and demo data.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/462

Create TolaTable factory

---

workflow/models.py

I need to provide this information in the JWT, so I know if a user is a superuser in the system or not.

Add SuperUser role option

---

MANIFEST.in

The template needs to be installed, so the system can use them to send emails.
- Added the workflow package data to MANIFEST
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/466

Include workflow package data to MANIFEST

---

search/tests/test_views.py

ElasticSearch's tests were working sometimes but it should work all the time.
- Sleep at least one second, so ES can create the indexes
- Generate org with new UUID in each new test

Fix ElasticSearch views' tests

---

factories/workflow_models.py
workflow/admin.py
workflow/migrations/0001_initial.py
workflow/models.py

Remove CodedField and CodedFieldData from TolaActivity
Removed their models, migrations, serializers, tests and use cases.

TOLA-499: Removing codedfield and codedfielddata

---

formlibrary/views.py
indicators/views.py
templates/formlibrary/beneficiary_form.html
templates/formlibrary/distribution_form.html
templates/formlibrary/trainingattendance_form.html
templates/indicators/collecteddata_form.html
templates/indicators/indicator_form.html
templates/indicators/indicator_form_modal.html
templates/registration/bookmark_form.html
templates/workflow/contact_form.html
templates/workflow/documentation_form.html
templates/workflow/siteprofile_form.html
templates/workflow/stakeholder_form.html
templates/workflow/workflowlevel1_form.html
templates/workflow/workflowlevel2_form.html
workflow/admin.py
workflow/migrations/0001_initial.py
workflow/models.py

Remove FormGuidance
Removed its models, serializers, migrations, tests and use cases.

TOLA-501: Remove FormGuidance
