toladata/TolaActivity

- Dockerfile
- tola/urls.py
Extended the Dockerfile and added gunicorn as a real wsgi server infront of the django application. Needed to extend the `tola.urls` module's `urlpatterns` variable otherwise static resources hadn't been able to be served by gunicorn - don't know why this works with `manage.py runserver`
> Use gunicorn at Dockerfile to spin up the django application

- feed/serializers.py
- feed/views.py
Added three new fields in the feed endpoint of workflowlevel1 to calculate for each workflowlevel1 the sums of the related workflowlevel 2 budget and actual expenses.
Implementation of the issue [#297](https://github.com/toladata/TolaDataV2/issues/297)
> Add new fields in the feed endpoint of workflowlevel1

- indicators/models.py
- indicators/test.py
- indicators/test_models.py
https://github.com/toladata/TolaDataV2/issues/366
> When creating a new level, it should inherit the organization from WorkflowLevel1

- feed/serializers.py
- feed/tests/test_stakeholderview.py
When a user was creating a new stakeholder, his/her organization wasn't being added to the stakeholder record. Now, this information is added when anybody creates a stakeholder.
Issue TolaDataV2/[#349](https://github.com/toladata/TolaDataV2/issues/349)
> Add current Org to new Stakeholder 

- .drone.yml
- .travis.yml
- docker-compose-dev.yml
- indicators/models.py
- search/exceptions.py
- search/models.py
- search/test_utils.py
- search/tests.py
- search/utils.py
The API is responding with 500 error if an indicator is not found in Elasticsearch. The best way to solve this situation is to log a warning and continue without breaking the API.
The indicator may not be in Elasticsearch because this value can be coming from fixtures or because Elasticsearch was temporarily deactivated.
> Ignore if Indicator to delete is not in Elasticsearch #360

- factories/user_models.py
- feed/serializers.py
- feed/tests/test_groupview.py
- feed/views.py
Give the URL of the group in the API. Remove the possibility to create groups via API.
Added the URL field in the GroupSerializer and changed the viewset of GroupViewSet to `ReadOnlyModelViewSet`. 
Related issue: TolaDataV2/[#405](https://github.com/toladata/TolaDataV2/issues/405)
> Add URL in GroupSerializer and Change GroupViewSet

- factories/workflow_models.py
- feed/tests/test_disaggregationtypeview.py
- feed/tests/test_groupview.py
- feed/tests/test_workflowteamview.py
- feed/views.py
The WorkflowTeam shouldn't be filtered by an organization when a user is part of the _OrgAdmin_ group. We should remove this filter but keep the workflowlevel1filter.
Related issue: TolaDataV2/[#406](https://github.com/toladata/TolaDataV2/issues/406)
> Remove the organization filter from workflowteam

- factories/workflow_models.py
- feed/tests/test_siteprofileview.py
- feed/views.py
When using query parameters to fetch data from the API, it should return the info filtered based on the params.
- Changed the `list` method in the SiteProfileViewSet. Getting the `queryset` from the ViewSet and applying the filter before applying the other filters.
Related issue: TolaDataV2/[#379](https://github.com/toladata/TolaDataV2/issues/379)
> Fix filter Sites under the Program Tab

- feed/permissions.py
- feed/tests/test_workflowteamview.py
- feed/views.py
The WorkflowTeams have to be filtered by the organization of the user, when an OrgAdmin fetches them.
No ticket related.
> Update the filter of queryset in the list of workflowteamview

- feed/permissions.py
- feed/tests/test_collecteddataview.py
- feed/tests/test_contactview.py
- feed/tests/test_documentationview.py
- feed/tests/test_indicatorview.py
- feed/tests/test_levelview.py
- feed/tests/test_milestoneview.py
- feed/tests/test_objectiveview.py
- feed/tests/test_portfolioview.py
- feed/tests/test_sectorview.py
- feed/tests/test_siteprofileview.py
- feed/tests/test_stakeholderview.py
- feed/tests/test_workflowlevel1view.py
- feed/tests/test_workflowlevel2view.py
- feed/tests/test_workflowteamview.py
When sending raw data like JSON, we were getting an error because of the data structure. This PR includes the fix and updates for all the tests that create or update data via API.
No ticket related.
> Fix the permissions when handling raw data

- Dockerfile
- docker-entrypoint.sh
- templates2/maintenance/index.html
Description
=====
At the moment, if the run migrations command exits with a code different than 0, then the server tries to start, exiting also with an error code and making Marathon to try again in a infinite loop to have the service working.
Purpose
======
If migrations could not be run, we display a static maintenance page, so we allow the developer to ssh into the server having the database problem and solve the issues there.
> Set maintenance page if migrations cannot be run

- requirements-dev.txt
- tola/settings/base.py
- tola/settings/dev.py
- tola/urls.py
Purpose
=====
Fixes the broken django-debug-toolbar for Development.
> Fix django-debug-toolbar on dev env

- factories/workflow_models.py
- tola/tests/test_utils.py
- tola/tests/test_views.py
- tola/views.py
Name of users from the registration form wasn't added to Tola User, it should be filled automatically.
Related issue: TolaDataV2/[#456](https://github.com/toladata/TolaDataV2/issues/456)
> Fix Given Name of new users is filled automatically

- feed/tests/test_stakeholderview.py
- feed/views.py
When a user fetches data from the endpoint list of stakeholder, it should get a list of no-duplicated stakeholders. 
Related issue: #803
> Fix duplicated stakeholder in the stakeholder list endpoint

- feed/tests/test_workflowlevel1view.py
- feed/views.py
WFL1 has to be associated with the user's organization.
Related issue: TolaDataV2/[#554](https://github.com/toladata/TolaDataV2/issues/554)
> Fix WFL1 isn't associated with an organization

- feed/permissions.py
- feed/tests/test_contactview.py
- feed/tests/test_indicatorview.py
The permission class wasn't checking the organization of **all** the workflowlevel1s in the creation and when the user sends an organization inside of the request, the permission wasn't checking that org as well.
Related issue: #827
> Fix the organization check of create permission

- feed/permissions.py
- feed/tests/test_workflowteamview.py
When a ProgramAdmin removes a member of their program, the member has to be removed from the program, in other words, the WorkflowTeam has to be deleted.
Related issue: TolaDataV2/[#536](https://github.com/toladata/TolaDataV2/issues/536)
> Fix the delete WorkflowTeam permission

- factories/workflow_models.py
- feed/permissions.py
- feed/tests/test_workflowlevel2sortview.py
A user should be able to create and edit workflowlevel2sort objects.
Related issue: TolaDataV2/[#574](https://github.com/toladata/TolaDataV2/issues/574)
> Fix workflowlevel2sort object permission

- tola/settings/base.py
- tola/settings/local.py
Purpose
========
We need this setting in order to have https URLs in Django Rest Framework API endpoints results.
> Make HTTPS settings configurable

- templates2/index.html
- tola/forms.py
- tola/tests/test_views.py
- tola/views.py
When a user is created in Activity, it should be created in Track with the same UUID.
Related issue: TolaDataV2/[#465](https://github.com/toladata/TolaDataV2/issues/465)
> Add Registration in Track functionality

- .travis.yml
- tola/settings/local.py
Purpose
======
Due to some incompatibility with JSON files in SQLite, we need to start running Travis tests with Postgres.
> Run Travis tests in Postgres

- feed/tests/test_workflowlevel2view.py
- feed/views.py
OrgAdmins should be able to view all WFL2 items associated with the Org's WFL1
Related ticket: TolaDataV2/[#511](https://github.com/toladata/TolaDataV2/issues/511)
> Update the list filter of WorkflowLevel2 view

- .drone.yml
- tola/settings/local.py
SQLite doesn't support the Django JSONField, so we need to start running drone.io tests with Postgres.
> Run drone.io tests with Postgres

- formlibrary/migrations/0005_auto_20171204_0203.py
To create a unique field, we need to create the field first and then change it to be unique.
> Fix the CustomForm migration script

- formlibrary/migrations/0005_auto_20171204_0203.py
- formlibrary/migrations/0006_auto_20171206_0942.py
We have to set the `form_uuid` field with unique values before altering it to be unique.
> Fix customform migration

- feed/tests/test_documentationview.py
- feed/views.py
The documentation is filtered by the program organization of a project but it should be by the program organization only.
Related issue: TolaDataV2/[#651](https://github.com/toladata/TolaDataV2/issues/651)
> Update filter of Documentation viewset

- tola/management/commands/loadinitialdata.py
- tola/management/commands/tests/test_loadinitialdata.py
Purpose
======
Now when we load the initial data through the factories, we set hardcoded IDs for each new record, but the database keeps the sequence at id=1.
> Reset SQL sequences after loading initial data

- workflow/models.py
- workflow/test_models.py
Purpose
======
In Demo environment, it's really annoying to see something like this:
Fallback to user's first and last name when the user is obfuscated.
Ticket
====
Sorry, no ticket.
> Fallback to user's name when printing TolaUser instance

- tola/tests/test_views.py
- tola/views.py
The Track URL in the index page should be the same in the Activity App.
Related ticket: TolaDataV2/[#649](https://github.com/toladata/TolaDataV2/issues/649)
Related PR: TolaTrack/[#346](https://github.com/toladata/TolaTables/pull/346)
> Update the Track URL in the index page

- templates2/registration/register.html
- tola/forms.py
- tola/tests/test_views.py
The checkbox to accept the Privacy Policy should be after the text.
Related ticket: TolaDataV2/[#646](https://github.com/toladata/TolaDataV2/issues/646)
> Update register new user form

- templates2/unauthorized.html
- tola/auth_pipeline.py
- tola/tests/test_oauth.py
The response when a user isn't in the white-listed domains should be more friendly than an error in the browser.
Related ticket: TolaDataV2?[#657](https://github.com/toladata/TolaDataV2/issues/657)
> Update the error response of white-listed domain

- tola/auth_pipeline.py
- tola/tests/test_oauth.py
- tola/tests/test_util.py
- tola/tests/test_views.py
- tola/util.py
- tola/views.py
The auth pipeline should trigger the creation of a user in TolaTrack as the registration form does.
Related ticket: #918
> Fix user sync track

- .drone.yml
Purpose
====
This is mostly a test. We need to deploy docker images with branch names, in order to be able to find them easily when typing `docker ps` in the server. We need that to execute cronjobs.
> Tag branch in Docker image

- tola/tests/test_views.py
- tola/urls.py
- tola/views.py
When a user logs out in Activity, they should be logged out from Track as well. So, we have to send a request to Track to log them out.
Related ticket: #932 
Related PR: TolaTables/[#374](https://github.com/toladata/TolaTables/pull/374)
> Log out the users in track as well

- tola/forms.py
- tola/tests/test_views.py
The Privacy disclaimer has to be required, a user cannot register in the system without accepting the terms.
Related ticket: TolaDataV2/[#839](https://github.com/toladata/TolaActivity/issues/839)
> Update the Registratrion Form

- feed/tests/test_customformview.py
- feed/views.py
The update endpoint of the Customform view has to send the right definition to Track.
The update endpoint was getting the definition of the custom form from the request data as a _list_ instead of a _unicode_ or _string_ obj. So, the JSON field was being parsed into a list. If we don't use the API form or request function, the fields in the request data are parsed.
Related ticket: TolaDataV2/[#716](https://github.com/toladata/TolaDataV2/issues/716)
> Fix the update endpoint of the CustomFormView

- tola/auth_pipeline.py
The passed email in the data object to Track for the user registration was wrong.
Related ticket: #950
> Fix user registration on Track

- workflow/admin.py
Add Organization column to Tolausers admin and allow filtering the same by Organization
> Adjust TolaUsers Admin to Include Organization Column: Fix #219

- docker-compose-dev.yml
- tola/__init__.py
- tola/tests/test_views.py
- tola/views.py
- workflow/signals.py
- workflow/tests/test_signals.py
It was added some more test. As I talked to @karrla and @andrewtpham, we'll have chargebee testing credentials for development and the demo env users cannot create organizations.
Related ticket: TolaDataV2/[#401](https://github.com/toladata/TolaDataV2/issues/401)
> Chargebee API integration

- tola/tests/test_track_sync.py
- tola/track_sync.py
- workflow/signals.py
- workflow/tests/test_signals.py
When an organization is created or updated on Activity it should be done on Track as well.
@sanjuroj I think you need this feature as well to keep the organization synchronized between Activity and Track, but we don't wanna execute the sync process in local environments. Therefore, we need an env variable called APP_BRANCH for the other environments, for example, "demo" and "production". Please, be aware of this change. If you don't create this env var, the synchronization won't happen.
Related ticket: #973
> Sync organization between Activity and Track 

- tola/tests/test_views.py
Purpose
======
When adding a Chargebee URL to docker-compose-dev, it broke one test in local.
> Fix broken test in local env

- setup.py
Fixes issue in ActivityAPI:
```
$ python manage.py test -v 2
Traceback (most recent call last):
File "manage.py", line 23, in <module>
execute_from_command_line(sys.argv)
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
utility.execute()
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
django.setup()
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
apps.populate(settings.INSTALLED_APPS)
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
app_config.ready()
File …
```
> Add track_sync to pkg

- templates2/registration/login.html
- tola/tests/test_views.py
- tola/urls.py
- tola/views.py
Sales would like to capture all users who log in to the demo site, so we should hide the social auth login buttons.
Related ticket: TolaDataV2/[#714](https://github.com/toladata/TolaDataV2/issues/714)
> Hide social auth login buttons in demo

- .drone.yml
- .travis.yml
- docker-compose-dev.yml
- tola/settings/local.py
- workflow/signals.py
- workflow/tests/test_signals.py
1. We need it for the ActivityAPI until we have Track working in parallel.
2. Makes it easier to develop locally.
3. In case something goes wrong with the connection with Track, it doesn't break the whole system.
> Add TOLA_TRACK_SYNC_ENABLED env var (default=True)

- tola/management/commands/synctrack.py
- tola/management/commands/tests/test_synctrack.py
We need a django-admin command to update the models workflowlevel1 and organization between Activity and Track.
Related ticket: TolaDataV2/[#795](https://github.com/toladata/TolaDataV2/issues/795)
> Django-admin command to sync Track with Activity

- tola/auth_pipeline.py
- tola/tests/test_oauth.py
When there is no whitelist defined in the system, users should be able to log in. But we're currently checking the whitelists all the time and when we don't have one, no users are allowed to sign in. This was fixed!
Related ticket: #987
> Fix auth pipeline

- docker-compose-dev.yml
We need to change the ChargeBee URL, so new organizations can add coupons and add-ons.
Related ticket: #997
> Revise chargebee url

- tola/auth_pipeline.py
- tola/tests/test_oauth.py
Fixes the exception when logging with Google:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line …
```
> Fix auth allowed pipeline

- tola/management/commands/synctrack.py
- tola/management/commands/tests/test_synctrack.py
We have to keep the projects and Tola users up to data on Track. They should be the same in Activity and Track.
We've already implemented a django-admin command to sync programs and organization. I just extended the functionality adding projects and tola users.
- We still have to improve the command, e.g., add the delete option.
Related ticket: #994
> Sync the WorkflowLevel2 and TolaUser models

- workflow/models.py
- workflow/tests/test_models.py
Fixes errors when inside the representation string there is a None value.
No ticket
> Fix workflow.models unicode representation

- feed/tests/test_budgetview.py
- workflow/models.py
The user needs to be able to update the Budget Amount and Actual Amounts for their WFL2 budgets.
I'm setting the default value of the fields as 0, even in the `save()` method to make sure that they won't be `None`.
Related ticket: #1038
> Fix error when updating Budget items

- docker-compose-dev.yml
- tola/settings/local.py
- workflow/signals.py
- workflow/tests/test_signals.py
We wanna notify the org admins when they have more editors than seats.
- Added the Email object and message.
- Added the DEFAULT_REPLY_TO env var.
Related ticket: https://github.com/toladata/TolaActivity/issues/998
> Add Org admin email to notify them about the seats

- .drone.yml
- tcp-port-wait.sh
The drone will always wait for the database before starting to run the tests.
Added a script to wait for the database for 120 seconds. If it exceeds the 2 min, it's gonna fail.
> Wait until the postgres is ready before test running

- workflow/models.py
Workflowlevel1 models uuid field can not be editable by  Activity API  create and update methods.
Added editable feature to uuid field with value of False.
Related ticket: Humanitec/ActivityAPI#175
> make workflowlevel1 model uuid non-editable

- workflow/signals.py
- workflow/tests/test_signals.py
The seat's calculation was wrong. New organizations with view-only users were having negatively used seats. We had to update the computation.
I'm checking the `OrgAdmin` is being removed instead of checking if the `ViewOnly` role is being added.
Related ticket: #197
> Fix the calculation of seats in the Group's signal

- workflow/models.py
- workflow/signals.py
- workflow/tests/test_models.py
ROLE_ORGANIZATION_ADMIN cannot be use as WorkflowTeams role.
Validation added to check WorkFlowTeam.role is not  ROLE_ORGANIZATION_ADMIN. 
Related ticket: #1075
> Make unable to create workflowteam with OrgAdmin role

- factories/workflow_models.py
- workflow/admin.py
- workflow/models.py
- workflow/tests/test_models.py
We don't need Contact model anymore because we have Contact model on microservice. Contact endpoint already removed by @Menda . 
Remove Contact model and it's dependencies from workflow module.
Removed codes which related to Contact model.
_Related ticket: Humanitec/ActivityAPI#172
>  Remove Contact model from workflow module

- requirements/pkg.txt
- setup.py
Installs extension django-oauth-toolkit-jwt
I tried locally this branch in Activity and everything is working as it was.
Related ticket: https://app.zenhub.com/workspace/o/humanitec/activityapi/issues/252
> Install django-oauth-toolkit-jwt

- requirements/pkg.txt
Upgrades django-oauth-toolkit-jwt to v0.3.
> Upgrade django-oauth-toolkit-jwt to v0.3

- tola/settings/dev.py
The third party addon `debug_toolbar` has been removed from requirements but was still initialised in the settings which caused problems when creating migrations for models.
Remove the unnecessary settings.
> Remove debug toolbar

- workflow/models.py
- workflow/tests/test_models.py
When we have many Organizations with similar project names, it's difficult to manage them in Django Admin.
> Add org name for WorkflowLevel1 representation

- workflow/signals.py
- workflow/tests/test_signals.py
In Kupfer we have the "Default Program" named with different letter cases sometimes, as people are introducing or modifying data manually. In this PR we ignore the case for that.
Also avoids duplication when creating WorkflowTeams after signals.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/128
> Improve data integrity when triggering signals

- workflow/signals.py
- workflow/tests/test_signals.py
When seats already exceeded and if we change roles of user who has already have seat or remove role of user then or admins still getting exceeded seats warning. We need to remove this warnings.
New flag added to check user has already seat and notification allowed to when user has no seat gains a seat.
_Related ticket: humanitec/ActivityAPI#283 and humanitec/ActivityAPI#285
> fix #283 #285 - remove extra notifications of exceeded seats when updating user groups

- workflow/signals.py
- workflow/tests/test_signals.py
Currently if a user deleted a budget line item from their WFL2 the WFL1 total budget is not being updated to reflect the new total (minus the deletion). If user delete budget item, total_estimated_budget and actual_cost of the related workflow2 should be updated.
post_save signals added for budget item. So, after budget item deleted, related workflowlevel2 automatically will be updated.
_Related ticket: Humanitec/ActivityAPI#392
> Close #392 - update workflow total_budget when related wfl2 budget deleted

- indicators/admin.py
- indicators/models.py
We need a export option for PeriodicTarget model on admin panel. 
ImportExportModelAdmin added as a base class to PeriodicTargetAdmin model.
_Related ticket: humanitec/ActivityAPI#404
> add export and import option to PeriodicTarget on admin panel

- factories/workflow_models.py
It's not possible to generate widgets via factory because the field name is wrong. We need to fix it to be able to create it.
> Fix wrong field name in Widget factory

- tola/tests/test_utils.py
- tola/utils.py
Create date isn't a model required field, so it's better to not use it in the token generator. Plus we're having some problems.
> Remove create date field from the Token generator

- workflow/signals.py
- workflow/tests/test_signals.py
Project's total_estimated_budget and actual_cost should be updated in the Budget model's signal.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/419
> Fix Budget signal wasn't calculating correctly

- search/tests/test_views.py
- search/views.py
We need to implement pagination, so we can be able to retrieve more than 10 results.
- Decided to use `search_after` of Elasticsearch, because it provides a live cursor.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/438
> Add pagination to Elasticsearch results

- tola/__init__.py
- workflow/signals.py
- workflow/tests/test_signals.py
TolaData team needs to have the emails separated by the categories, so they can classify emails.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/490
> Set up email categories

- workflow/models.py
- workflow/tests/test_models.py
If same domain used for two or more organization, this situation causes login problem for users. When user try to add new organization or update existing one with new oauth domain, We need to check are that oauth domain already used for another organization.
Clean_fields method added to check  oauth domains with other organizations. Therefore, if users try to add oauth domain which is already used in system, they will get validation error.
_Related ticket: humanitec/ActivityAPI#359
> add check for oauth domains are already used

- requirements/base.txt
- 1.11.17 of Dec 3, 2018
- For fixing open redirect vulnerability
CVE-2018-14574
moderate severity
Vulnerable versions: >= 1.11.0, < 1.11.15
Patched version: 1.11.15
django.middleware.common.CommonMiddleware in Django 1.11.x before 1.11.15 and 2.0.x before 2.0.8 has an Open Redirect.
- End of extended support until at least April 2020
> Change django-requirement to latest 1.11

- requirements/pkg.txt
CVE-2018-20060 More information
high severity
Vulnerable versions: < 1.23
Patched version: 1.23
urllib3 before version 1.23 does not remove the Authorization HTTP header when following a cross-origin redirect (i.e., a redirect that differs in host, port, or scheme). This can allow for credentials in the Authorization header to be exposed to unintended hosts or transmitted in cleartext.
> Fix urllib3 vulnerability

- workflow/signals.py
- workflow/tests/test_models.py
- workflow/tests/test_signals.py
Changing user organizations or adding users sometimes failed due to the chargebee seats check.
I commented out parts of code where that chargebee seat check was happening. I also commented out their respective tests.
> TOLA-396: Remove check seat calls and its tests
